import SectionHeading from '../components/SectionHeading'
import TechBadge from '../components/TechBadge'

const projects = [
  {
    icon: '📡',
    title: '1. RTK GPS Integration & Navigation Overhaul',
    objective: "Phase out the outdated Pixhawk-based navigation system in favor of a modern dual-antenna RTK setup for our autonomous rover to handle complex trajectory tracking.",
    bullets: [
      'Implemented dual-antenna RTK GPS hardware pipelines by writing custom Python firmware that constantly pushes RTCM corrections from the base station.',
      "Migrated away from Pixhawk's internal EKF (Extended Kalman Filter) by developing YAML configurations to launch and manage a custom ROS EKF node.",
      'Successfully achieved sensor fusion by combining IMU data from an onboard OAK-D camera with absolute heading and positional data from the new RTK modules.',
    ],
    techs: ['ROS', 'Python', 'EKF', 'RTCM'],
  },
  {
    icon: '⌨️',
    title: '2. Autonomous Keyboard Typing via Inverse Kinematics',
    objective: 'Create an autonomous subsystem capable of executing precise keystrokes natively without external telemetry networks.',
    bullets: [
      'Placed 4 ArUco markers surrounding a generic keyboard boundary for frame reference.',
      "Utilized the intrinsic matrix of a hand-mounted camera to establish precise 3D positioning mapping between the end-effector arm and the keyboard's spatial plane.",
      'Developed complex Inverse Kinematics (IK) algorithms that dynamically calculates joint angles to move the end-effector arm optimally to the position of any requested key.',
    ],
    techs: ['OpenCV', 'ArUco', 'Inverse Kinematics', 'Robotics'],
  },
  {
    icon: '🌐',
    title: '3. Webots Scalable Simulation Environment',
    objective: 'Eliminate hardware-testing bottlenecks by generating a high-fidelity digital twin of the rover physics.',
    bullets: [
      "Built a comprehensive Webots simulation environment derived from custom URDF (Unified Robot Description Format) models of the mechanical subteam's designs.",
      'Configured a continuous ROSbridge infrastructure that networks simulated sensory inputs/outputs (actuators, cameras) over to the actual autonomous ROS logic running inside a Docker container.',
      'Enabled 100% asynchronous and parallel software development workflow safely independent of physical hardware build timelines.',
    ],
    techs: ['Webots', 'URDF', 'ROSbridge', 'Docker'],
  },
  {
    icon: '👁️',
    title: '4. Advanced Obstacle Avoidance Pipelines',
    objective: null,
    bullets: [
      'Streamlined point cloud processing generated by the OAK-D stereo camera block to more effectively cull noise and identify steep obstacles.',
      'Constructed reliable 2D/3D dynamic occupancy grids mapping the navigable environment based off stereo depth.',
      'Refined the fundamental grid navigation code using the Theta* (Theta-star) algorithm, significantly enabling smoother, faster any-angle path avoidance.',
      'Engineered loss-of-signal fail-safes (rover recall) utilizing a software heartbeat signal logic over the telemetry network.',
    ],
    techs: [],
  },
  {
    icon: '🧠',
    title: '5. Edge AI Migration (YOLO)',
    objective: 'Decrease power consumption and decouple vision processing by migrating detection software across architectures.',
    bullets: [
      'Successfully oversaw the migration of the core object detection YOLO stack from a central Nvidia Jetson dependency block.',
      'Deployed natively onto the dedicated onboard NPU capabilities of an OrangePi.',
      'Integrated RKNN YOLO parsing directly against the camera pipeline, heavily freeing up compute resources for the navigation subsystems.',
    ],
    techs: [],
  },
]

export default function YonderDynamics({ navigate }) {
  return (
    <div className="max-w-4xl mx-auto">
      <button
        onClick={() => navigate('experiences')}
        className="text-secondary hover:text-secondary/80 mb-8 flex items-center gap-2 font-medium text-sm transition-colors"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
        Back to Experiences
      </button>

      <h2 className="text-3xl sm:text-4xl font-bold text-heading mb-3">Yonder Dynamics - Software Projects</h2>
      <p className="text-lg text-secondary/80 mb-10">Autonomous Systems Engineering & Optimization</p>

      <div className="glass rounded-2xl p-6 mb-10 border-l-4 border-secondary">
        <h3 className="text-xl font-bold text-heading mb-3">Overview</h3>
        <p className="text-slate">
          As the Software Lead at Yonder Dynamics, I manage the migration and development of our autonomous systems stack. My core contributions range from building real-time kinematics (RTK) integrations, overhauling navigation architectures, optimizing point cloud generation, and pioneering autonomous inverse kinematics logic for complex manipulation tasks.
        </p>
      </div>

      <div className="space-y-8">
        {projects.map((p) => (
          <section key={p.title} className="glass rounded-xl p-6 glass-hover transition-all duration-300 card-glow">
            <div className="flex items-center mb-4 gap-3">
              <span className="text-2xl">{p.icon}</span>
              <h3 className="text-xl font-bold text-heading">{p.title}</h3>
            </div>
            {p.objective && (
              <p className="text-sm text-slate mb-4">
                <strong className="text-heading">Objective:</strong> {p.objective}
              </p>
            )}
            <ul className="space-y-2 text-sm text-slate mb-4">
              {p.bullets.map((b, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-secondary mt-1.5 text-xs">&#9656;</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
            {p.techs.length > 0 && (
              <div className="flex flex-wrap gap-2">
                {p.techs.map((t) => <TechBadge key={t}>{t}</TechBadge>)}
              </div>
            )}
          </section>
        ))}
      </div>
    </div>
  )
}
